### ISSUE TITLE
Can we please have a release for Scala 2.11.0-M7?

### ISSUE THREAD

**Issue by etorreborre** [mdr/ascii-graphs#5]
Thanks!

**Comment by tribbloid** [comment]
+1 very useful library!

**Comment by jasongoodwin** [comment]
Yes I would love to use this!

**Comment by jzillmann** [comment]
There is a fork of this library which is on Scala 2.11: https://github.com/jlmauduy/ascii-graphs

(https://javalibs.com/artifact/com.github.jlmauduy/ascii-graphs_2.11)

**Comment by etorreborre** [comment]
Closing this old issue now.
